// <auto-generated />
using System;
using GoodHamburger.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GoodHamburger.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260331144829_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("GoodHamburger.Shared.Models.MenuItem", b =>
                {
                    b.Property<Guid>("MenuItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MenuItemId");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            MenuItemId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            Name = "X Burger",
                            Price = 5.00m,
                            Type = "Hamburger"
                        },
                        new
                        {
                            MenuItemId = new Guid("a2b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            Name = "X Egg",
                            Price = 4.50m,
                            Type = "Hamburger"
                        },
                        new
                        {
                            MenuItemId = new Guid("a3b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            Name = "X Bacon",
                            Price = 7.00m,
                            Type = "Hamburger"
                        },
                        new
                        {
                            MenuItemId = new Guid("a4b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            Name = "Fries",
                            Price = 2.00m,
                            Type = "Extra"
                        },
                        new
                        {
                            MenuItemId = new Guid("a5b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            Name = "Soft Drink",
                            Price = 2.50m,
                            Type = "Extra"
                        });
                });

            modelBuilder.Entity("GoodHamburger.Shared.Models.Order", b =>
                {
                    b.Property<Guid>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("GoodHamburger.Shared.Models.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MenuItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("GoodHamburger.Shared.Models.OrderItem", b =>
                {
                    b.HasOne("GoodHamburger.Shared.Models.Order", null)
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GoodHamburger.Shared.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
